/**
 * Document View Component
 * Main content area for displaying markdown files with sanitized HTML
 * 
 * Refactored to extract inline CSS to lib/document-dark-theme.ts (SRP)
 */

'use client';

import { useEffect, useState, useRef } from 'react';
import purify from 'isomorphic-dompurify';
import { DocumentHeader } from './DocumentHeader';
import { DocumentTabs } from './DocumentTabs';
import { useStore } from '@/lib/store';
import { injectDarkTheme } from '@/lib/document-dark-theme';
import type { ResearchProject } from '@/lib/types';

interface DocumentViewProps {
  project: ResearchProject | null;
  fileName: string | null;
  onFileSelect: (fileName: string) => void;
  onToggleFavorite?: (projectId: string, fileName: string) => void;
  isFavorite?: boolean;
}

export function DocumentView({
  project,
  fileName,
  onFileSelect,
  onToggleFavorite,
  isFavorite = false
}: DocumentViewProps) {
  const [html, setHtml] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Handle messages from iframe for internal link navigation
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === 'internal-link-click' && event.data?.href) {
        const href = event.data.href;
        // Check if it's a relative link to another file in the project
        if (!href.startsWith('http://') && !href.startsWith('https://') && !href.startsWith('//')) {
          // Extract filename from href (could be "./file.html", "file.html", "../file.html", etc.)
          const filename = href.split('/').pop()?.split('#')[0]?.split('?')[0];
          if (filename && project?.files.includes(filename)) {
            onFileSelect(filename);
          }
        } else {
          // External link - open in new tab
          window.open(href, '_blank', 'noopener,noreferrer');
        }
      }
    };

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [project, onFileSelect]);

  useEffect(() => {
    if (!project || !fileName) {
      setHtml('');
      return;
    }

    const loadFile = async () => {
      setLoading(true);
      setError(null);

      try {
        const response = await fetch(
          `/api/projects/${project.id}/files/${encodeURIComponent(fileName)}`
        );

        if (!response.ok) {
          throw new Error(`Failed to load file: ${response.statusText}`);
        }

         const data = await response.json();
         
         // For HTML files, allow more tags and attributes for proper rendering
         // For markdown-converted content, use stricter rules
         const isHtmlFile = fileName.endsWith('.html');
         
         if (isHtmlFile) {
           // For HTML files generated by our research agent, skip sanitization
           // These files are generated by our own code, not user input
           // Just remove script tags for basic security
           const htmlWithoutScripts = data.html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
           
           // Inject dark theme styles and link intercept script
           // Using extracted function from lib/document-dark-theme.ts (SRP)
           const themedHtml = injectDarkTheme(htmlWithoutScripts);
           setHtml(themedHtml);
         } else {
           // For markdown files, use strict sanitization
           const sanitized = purify.sanitize(data.html, { 
             ALLOWED_TAGS: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'br', 'strong', 'em', 'u', 'code', 'pre', 'a', 'ul', 'ol', 'li', 'blockquote', 'hr', 'table', 'thead', 'tbody', 'tr', 'td', 'th', 'img'],
             ALLOWED_ATTR: ['href', 'title', 'alt', 'src', 'class']
           });
           setHtml(sanitized);
         }

        // Add to recent
        useStore.getState().addToRecent(project.id, fileName);
      } catch (err) {
        console.error('Error loading file:', err);
        setError(err instanceof Error ? err.message : 'Failed to load file');
      } finally {
        setLoading(false);
      }
    };

    loadFile();
  }, [project, fileName]);

  if (!project || !fileName) {
    return null;
  }

  return (
    <div className="flex-1 flex flex-col bg-notion-bg-primary overflow-hidden">
      <DocumentHeader
        project={project}
        isFavorite={isFavorite}
        onToggleFavorite={() => onToggleFavorite?.(project.id, fileName)}
      />

       <DocumentTabs
        project={project}
        currentFileName={fileName}
        onFileSelect={onFileSelect}
      />

       <div className="flex-1 overflow-y-auto prose-container">
         {loading ? (
           <div className="flex items-center justify-center h-full">
             <div className="text-notion-text-secondary">Loading...</div>
           </div>
         ) : error ? (
           <div className="flex items-center justify-center h-full">
             <div className="text-red-500">Error: {error}</div>
           </div>
          ) : fileName?.endsWith('.html') ? (
            <iframe
              ref={iframeRef}
              srcDoc={html}
              className="w-full h-full border-0"
              sandbox="allow-same-origin allow-scripts"
              title={fileName}
            />
          ) : (
             <div className="px-6 py-8">
               <div
                 className="markdown-content text-notion-text-primary"
                 dangerouslySetInnerHTML={{ __html: html }}
               />
             </div>
         )}
       </div>
    </div>
  );
}
