/**
 * Document View Component
 * Main content area for displaying markdown files with sanitized HTML
 */

'use client';

import { useEffect, useState, useRef } from 'react';
import purify from 'isomorphic-dompurify';
import { DocumentHeader } from './DocumentHeader';
import { DocumentTabs } from './DocumentTabs';
import { useStore } from '@/lib/store';
import type { ResearchProject } from '@/lib/types';

interface DocumentViewProps {
  project: ResearchProject | null;
  fileName: string | null;
  onFileSelect: (fileName: string) => void;
  onToggleFavorite?: (projectId: string, fileName: string) => void;
  isFavorite?: boolean;
}

export function DocumentView({
  project,
  fileName,
  onFileSelect,
  onToggleFavorite,
  isFavorite = false
}: DocumentViewProps) {
  const [html, setHtml] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Handle messages from iframe for internal link navigation
  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === 'internal-link-click' && event.data?.href) {
        const href = event.data.href;
        // Check if it's a relative link to another file in the project
        if (!href.startsWith('http://') && !href.startsWith('https://') && !href.startsWith('//')) {
          // Extract filename from href (could be "./file.html", "file.html", "../file.html", etc.)
          const filename = href.split('/').pop()?.split('#')[0]?.split('?')[0];
          if (filename && project?.files.includes(filename)) {
            onFileSelect(filename);
          }
        } else {
          // External link - open in new tab
          window.open(href, '_blank', 'noopener,noreferrer');
        }
      }
    };

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [project, onFileSelect]);

  useEffect(() => {
    if (!project || !fileName) {
      setHtml('');
      return;
    }

    const loadFile = async () => {
      setLoading(true);
      setError(null);

      try {
        const response = await fetch(
          `/api/projects/${project.id}/files/${encodeURIComponent(fileName)}`
        );

        if (!response.ok) {
          throw new Error(`Failed to load file: ${response.statusText}`);
        }

         const data = await response.json();
         
         // For HTML files, allow more tags and attributes for proper rendering
         // For markdown-converted content, use stricter rules
         const isHtmlFile = fileName.endsWith('.html');
         
         if (isHtmlFile) {
           // For HTML files generated by our research agent, skip sanitization
           // These files are generated by our own code, not user input
           // Just remove script tags for basic security
           let htmlWithoutScripts = data.html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
           
           // Inject our dark theme styling to match the portal
           const darkThemeStyle = `
             <style>
               /* Override body styles to match dark theme */
               * {
                 font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', 'Lucida Grande', sans-serif !important;
               }
               
               body {
                 background: #191919 !important;
                 color: #ececec !important;
                 max-width: none !important;
                 margin: 0 !important;
                 padding: 2rem !important;
                 font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', 'Lucida Grande', sans-serif !important;
                 font-size: 14px !important;
                 line-height: 1.6 !important;
               }
               
               /* Update text colors */
               h1, h2, h3, h4, h5, h6 {
                 color: #ececec !important;
                 font-weight: 600 !important;
               }
               
               h1 {
                 font-size: 1.95em !important;
                 margin: 1em 0 0.5em 0 !important;
                 border-bottom: 1px solid #3d3d3d !important;
                 padding-bottom: 0.3em !important;
               }
               
               h2 {
                 font-size: 1.6em !important;
                 margin: 1em 0 0.5em 0 !important;
               }
               
               h3 {
                 font-size: 1.35em !important;
                 margin: 0.8em 0 0.4em 0 !important;
               }
               
               p, li, td, th {
                 color: #ececec !important;
                 line-height: 1.8 !important;
               }
               
               p {
                 margin: 0.8em 0 !important;
               }
               
               /* Update link colors */
               a {
                 color: #0ea5e9 !important;
               }
               
               a:hover {
                 color: #0b7285 !important;
               }
               
               /* Update table styling */
               table {
                 background: #2d2d2d !important;
                 border-color: #3d3d3d !important;
               }
               
               th {
                 background: #3d3d3d !important;
                 color: #ececec !important;
                 border-color: #3d3d3d !important;
               }
               
               td {
                 border-color: #3d3d3d !important;
                 background: transparent !important;
               }
               
               tr:hover td {
                 background: #373737 !important;
               }
               
               tr:nth-child(even) td {
                 background: rgba(255, 255, 255, 0.02) !important;
               }
               
               tr:nth-child(even):hover td {
                 background: #373737 !important;
               }
               
               /* Update code blocks */
               code {
                 font-family: 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace !important;
                 background: #2d2d2d !important;
                 color: #ececec !important;
                 padding: 0.2em 0.4em !important;
                 border-radius: 3px !important;
                 font-size: 0.9em !important;
               }
               
               pre {
                 font-family: 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace !important;
                 background: #2d2d2d !important;
                 border-color: #3d3d3d !important;
                 border: 1px solid #3d3d3d !important;
                 border-radius: 6px !important;
                 padding: 1em !important;
                 overflow-x: auto !important;
               }
               
               pre code {
                 background: transparent !important;
                 padding: 0 !important;
               }
               
               /* Update highlights */
               .highlight, mark {
                 background: rgba(14, 165, 233, 0.2) !important;
                 color: #ececec !important;
               }
             </style>
           `;
           
// Script to intercept link clicks and send to parent
            const linkInterceptScript = `
              <script>
                document.addEventListener('click', function(e) {
                  var target = e.target;
                  while (target && target.tagName !== 'A') {
                    target = target.parentElement;
                  }
                  if (target && target.tagName === 'A' && target.href) {
                    e.preventDefault();
                    window.parent.postMessage({
                      type: 'internal-link-click',
                      href: target.getAttribute('href')
                    }, '*');
                  }
                });
              </script>
            `;
            
            // Inject style after <head> tag or at the beginning if no head
            if (htmlWithoutScripts.includes('<head>')) {
              htmlWithoutScripts = htmlWithoutScripts.replace('<head>', '<head>' + darkThemeStyle);
            } else if (htmlWithoutScripts.includes('<!DOCTYPE')) {
              htmlWithoutScripts = htmlWithoutScripts.replace('<!DOCTYPE html>', '<!DOCTYPE html>' + darkThemeStyle);
            } else {
              htmlWithoutScripts = darkThemeStyle + htmlWithoutScripts;
            }
            
            // Inject link intercept script before </body> or at the end
            if (htmlWithoutScripts.includes('</body>')) {
              htmlWithoutScripts = htmlWithoutScripts.replace('</body>', linkInterceptScript + '</body>');
            } else {
              htmlWithoutScripts = htmlWithoutScripts + linkInterceptScript;
            }
            
            setHtml(htmlWithoutScripts);
         } else {
           // For markdown files, use strict sanitization
           const sanitized = purify.sanitize(data.html, { 
             ALLOWED_TAGS: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'br', 'strong', 'em', 'u', 'code', 'pre', 'a', 'ul', 'ol', 'li', 'blockquote', 'hr', 'table', 'thead', 'tbody', 'tr', 'td', 'th', 'img'],
             ALLOWED_ATTR: ['href', 'title', 'alt', 'src', 'class']
           });
           setHtml(sanitized);
         }

        // Add to recent
        useStore.getState().addToRecent(project.id, fileName);
      } catch (err) {
        console.error('Error loading file:', err);
        setError(err instanceof Error ? err.message : 'Failed to load file');
      } finally {
        setLoading(false);
      }
    };

    loadFile();
  }, [project, fileName]);

  if (!project || !fileName) {
    return null;
  }

  return (
    <div className="flex-1 flex flex-col bg-notion-bg-primary overflow-hidden">
      <DocumentHeader
        project={project}
        isFavorite={isFavorite}
        onToggleFavorite={() => onToggleFavorite?.(project.id, fileName)}
      />

       <DocumentTabs
        project={project}
        currentFileName={fileName}
        onFileSelect={onFileSelect}
      />

       <div className="flex-1 overflow-y-auto prose-container">
         {loading ? (
           <div className="flex items-center justify-center h-full">
             <div className="text-notion-text-secondary">Loading...</div>
           </div>
         ) : error ? (
           <div className="flex items-center justify-center h-full">
             <div className="text-red-500">Error: {error}</div>
           </div>
          ) : fileName?.endsWith('.html') ? (
            <iframe
              ref={iframeRef}
              srcDoc={html}
              className="w-full h-full border-0"
              sandbox="allow-same-origin allow-scripts"
              title={fileName}
            />
          ) : (
             <div className="px-6 py-8">
               <div
                 className="markdown-content text-notion-text-primary"
                 dangerouslySetInnerHTML={{ __html: html }}
               />
             </div>
         )}
       </div>
    </div>
  );
}
